## Numpy
* Numerical Python

### Importing numpy library

In [2]:
import numpy as np

### Array

### 1-D

In [8]:
mylist_1 = ["apple", 56]
print(mylist_1)

myarray_1 = np.array(mylist_1)
print(myarray_1)

['apple', 56]
['apple' '56']


In [9]:
print(type(mylist_1))
print(type(myarray_1))

<class 'list'>
<class 'numpy.ndarray'>


### 2-D

In [28]:
mylist_2 = ([1,2,3], [4,5,6], [7,8,9])
print(mylist_2)

print("\n")

myarray_2 = np.array(mylist_2)
print(myarray_2)

([1, 2, 3], [4, 5, 6], [7, 8, 9])


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
print(type(mylist_2))
print(type(myarray_2))

<class 'tuple'>
<class 'numpy.ndarray'>


## range Vs arange

### range

In [30]:
for i in range(1,11,1):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [43]:
np.array(list(range(1,11,1)))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
tuple(range(1,11,1))

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

### arange

In [46]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
# Zeros:
print(np.zeros(3))

print("\n")

print(np.zeros((5,6)))

[0. 0. 0.]


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [56]:
# ones:
print(np.ones(5))

print("\n")

print(np.ones((5,6)))

[1. 1. 1. 1. 1.]


[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [67]:
# diagonal (1):
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### reshape

In [76]:
# reshape:
x = np.ones((3,6))
print(x)
print("\n")

y = x.reshape(2,9)
print(y)
print("\n")

z = x.reshape(6,3)
print(z)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [78]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [83]:
a.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

#### linspace

In [92]:
np.linspace(1,7,25)

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75, 6.  , 6.25,
       6.5 , 6.75, 7.  ])

#### reshape Vs resize

In [94]:
x = np.arange(1,11,1)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
x.reshape(10,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [96]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
x.resize(10,1)

In [98]:
x

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

### Generating random values

#### rand
* print values between (0 and 1)

In [99]:
np.random.rand(5)

array([0.58400548, 0.63148892, 0.70141144, 0.89430507, 0.95933212])

In [105]:
np.random.rand(3,5)

array([[0.69189038, 0.22550978, 0.19253426, 0.41267327, 0.23466839],
       [0.21109379, 0.07816828, 0.49757195, 0.25311122, 0.95322533],
       [0.95191322, 0.22584499, 0.49492616, 0.65950389, 0.35617162]])

#### randn

In [107]:
np.random.randn(5)

array([-0.41187435,  0.12176722, -0.39305932,  0.85095104,  0.37967105])

In [108]:
np.random.randn(3,5)

array([[ 1.31465379, -0.16611676,  0.06181087,  0.22556123, -1.20819104],
       [-0.88074953, -0.77752823, -0.68899592, -2.05182504, -0.09851024],
       [-0.86827738, -0.82112267,  1.31642106, -0.47300405, -0.8444068 ]])

#### randint

In [137]:
np.random.randint(3,7,5)

array([3, 6, 4, 3, 3], dtype=int32)

In [143]:
np.random.randint(0,2, (5,6))

array([[1, 1, 1, 1, 0, 1],
       [1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [0, 0, 1, 1, 0, 1],
       [0, 0, 0, 1, 0, 0]], dtype=int32)

### dir

In [144]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'a